postgres:
    image: postgres:9.6.3
    volumes:
        - ./db/init:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
    ports:
        - 5432:5432